language: node_js
node_js:
- "0.10"
- "4"
require: sudo
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libkrb5-dev
  # update the compiler for node-gyp
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5
script: "npm run-script tap-pessimist"
